         document.write("<table border=1")
        document.write("<tr>")
        document.write("<th>Name</th>")
        document.write("<th>Hours</th>")
        document.write("</tr>")
        document.write("<tr>")
        document.write("<td>Java</td>")
        document.write("<td>420 hrs</td>")
        document.write("</tr>")
        document.write("<tr>")
        document.write("<td>Python</td>")
        document.write("<td>300 hrs</td>")
        document.write("</tr>")
        document.write("<tr>")
        document.write("<td>Power Bi</td>")
        document.write("<td>2000 hrs</td>")
        document.write("</tr>")
        document.write("</table>")